[package]
name = "gotham-static-file-handler"
version = "0.1.0"
authors = ["Daniel Wagner-Hall <dawagner@gmail.com>"]

[dependencies]
gotham = "0.2"
gotham_derive = "0.2"
hyper = "0.11"
mime = "0.3"
mime_guess = "2.0.0-alpha.3"
serde = "1"
serde_derive = "1"
